### ISSUE TITLE
Update search box widget to submit to new DB Finder

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#103]
The nand-based Database Finder will be replaced on Monday (9/17) with a LibGuides-based Database Finder. The home page search box widget submits searches to the Database Finder, and will need to be updated to use the new location.

Zadrozny can supply details regarding the new destination.

**Comment by kzadrozny** [comment]
There is an API for the A-Z List, but it doesn't look like it has anything search specific:
Get A-Z assets | /1.2/az | GET |  
Update single A-Z asset | /1.2/az/:id | PUT |  
Update A-Z asset collection | /1.2/az/collection | PUT |  
Create single A-Z asset | /1.2/az | POST |  
Create A-Z asset collection | /1.2/az/collection | POST

[Full documentation](https://uchicago.libapps.com/libguides/api.php?action=2&version=1.2) (need to log in)

**Comment by bbusenius** [comment]
After talking to @dbietila, we decided to set the form action to the handle `/dbfinder`.
