### ISSUE TITLE
Support migration to LibAnswers

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#134]
- [x] We are going from 47 Knowledge Tracker forms to 11 local forms + 8 native Native LibAnswers forms. We need to convert our forms and make them accessible/mobile-friendly. David Bottorff has a list of form mappings. Coordinate with Keith to ensure that are new forms are submitting with the correct syntax.
- [x] Insert new chat widget at all locations where Ask a Librarian chat widget currently appears. We can start this on test Wagtail.
- [x] Catalog Can't Find It will convert earlier. Will become an OLE form.
- [ ] Catalog Report a Record Problem will need a way to pass bib information from the record with the form submission.
- [ ] Reference would like LibWizard stats displayed on a Loop page. They believe there is an API to allow the html to be embedded.
- [ ] Reference and Research AULs are interested in use the LibAnswers public FAQs pages. We need to style these to resemble Library pages. Also bring to WCG to discuss administration/linking/maintenance of these pages.

**Comment by kzadrozny** [comment]
Going from DBot's spreadsheet, these are the KT forms that are being migrated to LibAnswers:
- [ ] Ask a Librarian: Contact Form
- [ ] Ask A Law Librarian: Contact Form
- [ ] Contact   Circulation
- [ ] Ask Law Circulation / Access Services
- [ ] Contact the ID and Privileges Office
- [ ] Contact the Special Collections Research Center
- [ ] LibAnswers form - Tech Services (NEW FORM?)

And these are the forms that will be web forms:
- [ ] 
- [ ]

**Comment by kzadrozny** [comment]
@dbietila Are all issues resolved on this migration?

**Comment by kzadrozny** [comment]
This project has been completed.
