### ISSUE TITLE
Tweaks to Digital Collection mocks

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#138]
**On Collection page**

- Change "Catalog Map Browse" to "Browse this collection in the Library Catalog"
- Change "Subject Map Browse" to "Browse all maps by subject"
- Break apart subject terms, and omit “Map” as a term. So, first record would instead have:
Land use
Real property
Chicago
Illinois

- Change "Reproduction Rights" to "This collection is licensed under a Creative Commons Attribution-ShareAlike 4.0 License, except for materials published prior to 1924, which are in the public domain."

**On Collection Object page**

- In Other Ways to View, the explanatory text needs to be subordinate to the service names. It is too prominent right now.
- EL suggests making the metadata layout rows closer to the styling of catalog bib data - tighter and with break lines between rows https://catalog.lib.uchicago.edu/vufind/Record/1177456
- Move “Link and Share” to “Share this” and place immediately below UV. It should be a drop down menu with social media sharing options.
- Move Permalink back to being the last metadata fields and label it “URL for this record”
- Move “Cite this” adjacent to “Share this”. Also a drop down
- Style "Share this" and "Cite this" similarly to VuFind, if possible

**Comment by kzadrozny** [comment]
[Collection page mock](https://uchicago-library.github.io/LibPattern/digital-map-collection.html) and [Object Item page mock](https://uchicago-library.github.io/LibPattern/digital-map-collection-item.html) have both been updated with these requests.
