### ISSUE TITLE
Integrate LibAnswers chat widgets with Wagtail

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#145]
As part of the LibAnswers migration, we need to ensure that the associated chat widgets will work in Wagtail on launch.

We currently have four chat widgets in Wagtail (law, uofc-ask [used on main page, Crerar, and Eckhart], ssa, and dissertation office.

With LibAnwers, we can also fold in SSA with the main account, leaving us with three widgets.

Each LibAnswers widget consistent of a line of code to be placed in the page <head> and another line to be placed in the <body> wherever the chat box ought to be positioned. The code snippets for each of the three widgets are as follows:

**Ask a Dissertation Office Librarian**
```
<head>
<script src="https://v2.libanswers.com/load_chat.php?hash=946689341a093741c4e12f427047faa2"></script>

<body>
<div id="libchat_946689341a093741c4e12f427047faa2"></div>
```

**Ask a Librarian** (Main, Crerar, Eckhart, SSA)
```
<head>
<script src="https://v2.libanswers.com/load_chat.php?hash=7d40a704e1d39b1c6a20f5c35faf1aaf"></script> 

<body>
<div id="libchat_7d40a704e1d39b1c6a20f5c35faf1aaf"></div>
```

**Ask a Law Librarian**
```
<head>
<script src="https://v2.libanswers.com/load_chat.php?hash=a4866467f8e4db1dd88568e7c8b01c05"></script>  

<body>
<div id="libchat_a4866467f8e4db1dd88568e7c8b01c05"></div>
```

**Comment by bbusenius** [comment]
I'm assuming that we also need to update the code responsible for displaying chat status in the main navigation and on the buttons displayed on AskPages. Is that correct?

Assuming that's the case, I need to find the correct api for this. To do that I'm looking for the embed codes in the LibAnswers admin, so I can be sure I grab the correct corresponding API. The embed codes I'm seeing look very different from the ones you posted above. I think they're for v1. I might not have access to the admin for v2, I'm not sure. In any case, can you post a link to the admin screen that generates these embed codes?

**Comment by dbietila** [comment]
The screen I'm seeing with embed codes is at https://uchicago.libanswers.com/admin/chatbrowse?m=e

**Comment by dbietila** [comment]
This seems to be the chat status API: https://uchicago.libanswers.com/admin/widgets?m=2&api=chat_status

**Comment by dbietila** [comment]
But you're right - I see another page with chat widget embed code at https://uchicago.libanswers.com/admin/widgets?m=1 . I'm not sure which is correct.

**Comment by bbusenius** [comment]
This is done but it could use some styling attention from @kzadrozny. Kicking this to her.

**Comment by kzadrozny** [comment]
The majority of these styling changes were made in each widget within Springshare. I am hoping we can keep widget-specific styling within that platform. I made some ADA compliance changes to the code, but otherwise, anything else that needs to be done on launch will be on individual Wagtail pages.
