### ISSUE TITLE
News Site Styling Fixes

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#169]
Issues that have been revealed on the test site:
- Solo / Duo images do not have expected styling
- Some categories do not have colors matches to them for the news feed
- `.centermain` has 0 padding in mobile

Need to:
- Add stying for solo / duo images
- Confer with @bbusenius about category classes and assign colors for the feeds on the home page and Library Kiosks
- Add padding for `.libnewspage.centermain` in mobile

**Comment by kzadrozny** [comment]
Category status:
**Bold** = no class
Italic = Still using?

_- [ not in drop down ] = hours-access_
- Business &amp; Economics
**- Digital Scholarship**
- Events = events
- Exhibit News = exhibits
- From the Director = from-the-director
**- Humanities & Social Sciences
- Law
- Library in the News**
- People = people
- Research = research
- Resources = resources
**- Science**
- Spaces = spaces
**- Special Collections**
- Spotlight = spotlight
- Teaching = teaching

**Comment by bbusenius** [comment]
All category names should map to lower-case-slugified css classnames. Ampersands are stripped out. I also added a category for Hours & Access so it should now appear in the drop down.
