### ISSUE TITLE
Add automatic modules to Collecting Area Template

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#17]
### Related documentation:
Three (and a half) Auto-Modules needed, as seen in the full [Spec spreadsheet](https://docs.google.com/a/uchicago.edu/spreadsheets/d/1J8aZLi3vsgzNEtcWLihBqvf1BdRWmoJlsf_2SWsXWOc/edit?usp=sharing)

### 1. Subject Specialist(s)
Data model needs to pull:
- Image source of staff profile photo
- Title of page (staff name)
- staff title
- staff contact info (the same data as collections, but with the profile photo added)
Needs to support multiple staff; ALL staff that have self.subject listed in their subjects

### 2. Highlighted Collections & Exhibits
Data model needs to pull:
- Image source of thumbnail
- Title of page
- Content of "short abstract"
From the page chosen via "page chooser"; not repeatable, but 4 instances

### 3. Related Collections
Pulls all collections tagged with subject chosen for self.CollectingAreaPage:
- Title of page
- Url of page

### 4. Related Exhibits
Pulls all exhibits tagged with subject chosen for self.CollectingAreaPage:
- Title of page
- Url of page

**Comment by bbusenius** [comment]
This issue is now being addressed in the [Collection-Hub-2](/uchicago-library/library_website/tree/Collection-Hub-2) branch

**Comment by kzadrozny** [comment]
@bbusenius 
Last step:
related_collecting_area needs get context and def tuples.
