### ISSUE TITLE
News Story: Exhibit item display issues

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#173]
## Online Only
If an exhibit is online only, the "Visit the Exhibit" h2 shows up with no data. See this story for an example: https://www.lib.uchicago.edu/about/news/online-exhibit-united-states-supreme-court-portraits-and-autographs/

## Sidebar in Story
Sidebar widget are out of order and have incorrect headers
- All widget / module headers should be `h3` ; some are `h2`
- The Rich Text widget should come before "Current Exhibits." The order should be "Exhibit," "Rich text," Current Exhibits," etc... See this story as an example: https://www.lib.uchicago.edu/about/news/discovery-collection-memory-the-oriental-institute-at-100/

**Comment by bbusenius** [comment]
It seems to me that the "Visit the Exhibit" stanza should only show up if the associated exhibit is a _current_ exhibit. Does that make sense? If we do it that way, the stanza will also disappear for exhibits that were "visitable" but are no longer open.

**Comment by kzadrozny** [comment]
I think this makes perfect sense and will solve some patron confusion issues the staff have brought up in the past.
