### ISSUE TITLE
Style Enhancements to Staff Browse

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#18]
- removed table headers [visually only, keep for ADA]
- Italicize dept breadcrumb
- Make last dept stand out somehow
- Add area in table for" specialties" (new snippet)
- Move "quick numbers" out of table and make more prominent
- [NEW] Add breadcrumbs to staff and department views

**Comment by johnjung** [comment]
We don't use our site breadcrumbs on the library directory--I think we should integrate the department directory, the staff directory, and department and staff pages into the site's breadcrumb navigation. Related to this, in some situations we also use a url parameter where that might not be the best solution: /about/directory/?view=staff might be better as /about/directory/staff/. 

Kathy, if you'd like me to open a separate issue for this I could, but I'd like to look at this stuff as holistically as we can.

**Comment by kzadrozny** [comment]
This is a good idea and I think keeping like concepts together in one issue is the way to go. I'll add this addition to the specs.

**Comment by kzadrozny** [comment]
# For white boarding session
## Sidebar / Filtering
- Harvard's filtering is nice, but not responsive: http://library.harvard.edu/staff-directory
- Utilize our Off-Canvas left sidebar with this filtering: https://medium.com/@mibosc/responsive-design-getting-advanced-filtering-right-bbd6c04f09e1

## Body
- Bootstrap built in collapse: https://v4-alpha.getbootstrap.com/components/collapse/
- Live filter search: https://www.w3schools.com/howto/howto_js_filter_lists.asp

**Comment by kzadrozny** [comment]
Completed: https://www.lib.uchicago.edu/about/directory/?view=staff

**Comment by kzadrozny** [comment]
Completed: https://www.lib.uchicago.edu/about/directory/?view=staff
