### ISSUE TITLE
Staff Browse - Load all in one Page

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#19]
Load all staff in one page, rather than splitting staff results into separate pages.
(Additionally check if Exhibits and Collections browse load all in one page, or if paginated.)

**Comment by johnjung** [comment]
I can do this, but it adds some download time: 75% for the staff browse on my development machine (from 2 seconds to 3.5 seconds.) Since they're browses, not searches, hopefully we'll be able to speed that up with caching.

**Comment by johnjung** [comment]
This is in place in commit #a8fe8f, this will get pushed to production soon.
