### ISSUE TITLE
Caching of views needed

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#192]
##  Needed
After the rollout of [wagtail-cache](https://docs.coderedcorp.com/wagtail-cache/stable/index.html), standalone views are only partially cached. Performance of these views can be improved by applying the `@cache_page` or `@method_decorator` to them. More information about caching views can be found [here](https://docs.coderedcorp.com/wagtail-cache/stable/getting_started/install.html#caching-views).

### Views that need this
- [Public site staff directory](https://www.lib.uchicago.edu/about/directory/?view=staff&library=The+University+of+Chicago+Library&subject=All+Subject+Specialists)
- [Public site departments directory](https://www.lib.uchicago.edu/about/directory/?view=department)
- [Spaces browse](https://www.lib.uchicago.edu/spaces/)
- [Collections, Exhibits and Subjects browses](https://www.lib.uchicago.edu/collex/)

### Additional information
Template fragment caching is already in place in some places. Look at issue #71

**Comment by kzadrozny** [comment]
@bufordrat Did this issue get resolved with #211 ?

**Comment by bufordrat** [comment]
Yeah; the caching wasn't having any observable effect on performance, but as I recall, we decided to leave it in there anyway.
