### ISSUE TITLE
RSS feeds for the news site

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#198]
## New feature request
RSS feeds are needed for the news section of the public site. A separate RSS feed should be created for every category on the site:

![image](https://user-images.githubusercontent.com/7826429/66227226-5e23b680-e6a2-11e9-87b9-ba809d8dc5ab.png)

This should most likely be done as a Django `view` where category names are passed as part of a `GET` request.

## Not needed?
- There has been no preference expressed regarding the format of the urls
- There has been no request to have the feeds accessible as part of the templates

**Comment by kzadrozny** [comment]
I'm unsure if a separate RSS feed is required for each category.  It may only bee needed for the ones that match Library Kiosks. Verify with WCG.
