### ISSUE TITLE
Page Owners report for departed staff

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#215]
Rachel has requested a Page Owners Report for Yasmin Omer and Catherine Niehaus.

Yasmin Omer is no longer library staff, and she does not appear to be on the select list. She does still own some pages, though. Is it possible to allow inactive staff to be selected from the menu for reporting?

Also, I can select Catherine Niehaus from the reports interface, but I keep getting 504 Gateway Timeout messages when requesting this report.

**Comment by bbusenius** [comment]
It looks like this issue has competing interests with #195 we'll need to discuss ramifications.
