### ISSUE TITLE
Unpublished news stories that are scheduled to be published appear on kiosk pages

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#228]
##  Expected behavior
When an unpublished news page is scheduled to go live it should _not_ appear on any kiosk page until it goes live.

## Actual behavior
Unpublished news pages that are scheduled to go live, appear on kiosk pages before they go live.

### Steps to reproduce
Create a news page and set the "Go live date/time" field under " Scheduled publishing" on the "Settings" tab to a time in the future. Also select one of the kiosk pages under the "Publish to" dialog  in the "Content" tab. Now publish the page. The icon next to the page name will say "Scheduled" and the page will not be live, however, if you go to the kiosk page, you will see the story in the news section.  

### Related code
This is most likely a problem with the `get_news` function in `base/models.py`. The queryset is probably missing a `live()` filter.

## Other information:**
I had trouble testing this on my dev box. For some reason scheduled pages went live immediately. It might be better to test this on `nest`.

**Comment by bufordrat** [comment]
Excellent--looks perfect!
