### ISSUE TITLE
Bad link on staff directory

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#230]
## Problem
The "Schedule an Appointment" link in the sidebar of the [staff directory](https://www.lib.uchicago.edu/about/directory/) returns a "404 Not found" when clicked. It has been requested that this link be removed. ~~This link appears in two templates~~.

## Related files
~~`ask_a_librarian/templates/ask_a_librarian/ask_page.html`~~
`units/templates/units/unit_index_page.html`

**Comment by bbusenius** [comment]
@dbietila or @kzadrozny do you know if this should definitely be removed or does the link need to be updated instead?

**Comment by dbietila** [comment]
We will probably looking at embedding the Springshare appointment widget into Wagtail pages when we have time. But that will behave differently and have different placement, so I think the current form can be removed.

**Comment by bbusenius** [comment]
Fantastic! I'll get rid of it then. Thanks!
