### ISSUE TITLE
Alert banners should display on browse views

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#271]
## Expected behavior
Alert banners should display on all library website pages, including browse views.

## Actual behavior
Alert banners display on normal Wagtail pages but not on browse views

### Steps to reproduce
[Go to a browse view](https://www.lib.uchicago.edu/about/directory/?view=staff) when a banner alert is published and you will not see an alert displayed. A banner alert will display on normal Wagtail pages though.

## Affected views
- https://www.lib.uchicago.edu/about/directory/?view=staff
- https://www.lib.uchicago.edu/collex/
- https://www.lib.uchicago.edu/about/news-events/events/
- https://www.lib.uchicago.edu/spaces/

**Comment by kzadrozny** [comment]
Looks like this issue has been resolved but didn't get closed when the branch was merged.
