### ISSUE TITLE
Emergency Hours Override

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#275]
A setting in Wagtail to override the hours displayed in the main navigation.

**Behavior**
- "Emergency Hours" will be a boolean Site Setting in Wagtail admin
- If "Emergency Hours" is toggled, it will activate an `if` statement in the navigation bar
- This `if` statement will hide the dynamic hours and drop down
- Link text will default to "View Hours" but will draw from a `CharField` so it will be customizable (This link will retain the clock icon)
- This link will lead to the hours page, which will be modified to show the adjusted hours

This approach will keep the dynamic hours logic intact and will allow a Wagtail user to toggle the emergency hours status.

**Comment by kzadrozny** [comment]
The site setting would be similar to how the footer is populated on the BMRC site: https://github.com/uchicago-library/bmrc/blob/master/site_settings/models.py

**Comment by dbietila** [comment]
I think we may need to have the "View Hours" text be customizable, but otherwise this looks very good.

**Comment by bbusenius** [comment]
I updated the ticket to reflect customizable link text.

**Comment by kzadrozny** [comment]
This issue has been resolved and is functioning on production as expected. We have noticed that the cache needs to be cleared via the Wagtail setting and apache may have to be restarted in order for the changes to be viewable.
