### ISSUE TITLE
Library spaces page hours widget bug

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#294]
## Expected behavior
When "show hours in sidebar" boolean is not checked, the LibCal hours table should not show-up in the sidebar.

## Actual behavior
LibCal hours table shows up in sidebar whether the "show hours in sidebar" boolean is checked or not. I tested removing the LibCal ID with no change in behavior.

### Steps to reproduce
Seen on the Reg spaces page: https://www.lib.uchicago.edu/admin/pages/1797/edit/#tab-widgets

**Comment by bbusenius** [comment]
Strangely it looks like this issue only effects `LocationPages` because the widget on the [Dissertation Office page](https://www.lib.uchicago.edu/research/scholar/phd/) works fine.
