### ISSUE TITLE
Switch Reference phone number to SMS number

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#311]
While the building is closed, we don't want to be promoting the voice phone number for the Reference Desk. At the same time, reference staff wish to pilot an SMS-based chat service. We should replace occurrences of the voice number with the SMS number.

Also, clearly indicate that the new number is for texting with a label of "Text us" or "SMS Text Reference" and an icon of a cell phone (in contexts where an icon needs to appear).

Pages where this number occurs:
https://www.lib.uchicago.edu/research/help/ask-librarian/
https://www.lib.uchicago.edu/about/directory/ (in sidebar)
"Research and Teaching Support" unit on https://www.lib.uchicago.edu/about/directory/?view=department

LibGuides owned by the "Ask a Librarian" account.
Ie: http://guides.lib.uchicago.edu/articles

**Comment by dbietila** [comment]
I believe that the SMS # is 1-773-825-6777

**Comment by kzadrozny** [comment]
Change "Secondary number" field to an SMS field.
- Change label
- Change icon

**Comment by kzadrozny** [comment]
Changes from Web Content Group
- Email icon (envelope) size too large / out of scale with other icons
- Add "(Text)" between icon and number
- See if we can add link to number that allows a text app to open up and start a text message
- Change "SMS Reference Help" on Quick Numbers to "Text Message"
