### ISSUE TITLE
CGIMAIL Form Page

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#317]
## The problem
Currently we have a bunch of disparate `CGIMAIL` forms scattered throughout the website. Some of these are raw html pages in Wagtail while others are old static PHP pages on `forms2.lib`. The user experience of these forms is less than ideal because they often have a different design from our main library website. Additionally the server-side form processing of the forms, displays an unstyled and unbranded page after submission. We need a Wagtail CGIMailPage type to deal with these problems and improve the user experience.

## Desired features
-  Forms should auto-populate to the greatest degree possible. For forms that interact with the catalog this can be [done using the itemServlet API on forms2](http://forms2.lib.uchicago.edu/lib/searchform/itemServlet.php?format=json&bib=5040507&barcode=64285052), which can get item information from `bib` and `barcode` parameters. As a "nice to have" part of this feature, the forms should detect if a user is Shibboleth authenticated and populate as much personal information in the form as possible. 
- Ability to set fields as required
- Ability to set input fields as hidden
- Ability to group form fields into form-groups within a fieldset or form section
- Allow the author to set additional "thank you / success" text to display in addition to the `CGIMAIL` receipt.
- Display the `CGIMAIL` receipt in the body of the page after submission (rather than rout them to an unstyled page).
- Adherence to[ the CGIMAIL documentation](https://www2.lib.uchicago.edu/keith/tmp/cgimail.html) including the required, hidden `rcpt` field.
- Forms should be fully accessible [@kzadrozny will assist with frontend ADA code].
- As part of meeting accessibility standards, the form should have a way of grouping fields into fieldsets in the configuration or creation process [See [accessible form code](https://github.com/uchicago-library/uchicago-library.github.io/blob/master/docs/code-resources.md#forms) in our docs].
- Accommodate the porting of all required forms below

### Required  web forms to be supported
- [x] [Ask a Librarian Request Instruction](https://www.lib.uchicago.edu/research/teaching/research-instruction-courses/request/)
- [x] [Ask a Librarian Tour Request Form](https://www.lib.uchicago.edu/research/teaching/tours/tour-request/)
- [x] [Ask a Librarian Ask the Dissertation Office Contact Form](https://www.lib.uchicago.edu/research/scholar/phd/services/askdo/)
- [x] [D'Angelo reference FacultyWeb Request](https://www.lib.uchicago.edu/law/ask-librarian-law/facultyweb/)
- [x] [Circulation Fisher Express Request](https://www.lib.uchicago.edu/borrow/requesting/fisher-express/)
- [x] [D'Angelo Access Services D'Angelo Law Library Carrel Request Form](https://www.lib.uchicago.edu/law/ask-librarian-law/carrelrequest/)
- [x] [D'Angelo Access Services Library Paging Service for Law School Students & Staff](https://www.lib.uchicago.edu/law/ask-librarian-law/paging-service/)
- [x] [IPO Regenstein Faculty Study Request](https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/regenstein-faculty-studies/faculty-study-request/)
- [x] [IPO Proxy Borrower Request](https://www.lib.uchicago.edu/borrow/access-privileges/uchicago-faculty-students-and-staff/proxy/)
- [x] [IPO Campus Card Requests](https://www.lib.uchicago.edu/borrow/access-privileges/library-cards-and-account-information/campus-card/)
- [x] [SCRC Permission to Publish](https://www.lib.uchicago.edu/scrc/visiting/permission/)
- [x] [SCRC Request SCRC Instruction](https://www.lib.uchicago.edu/scrc/visiting/teaching/request-instruction/)
- [x] [Tech Services Digital Photography Service Order Form](https://www.lib.uchicago.edu/about/directory/departments/pres/services/digital-photography-service-order-form/)

### Required VuFind forms to be supported
- [x] [Report a Record Problem](http://forms2.lib.uchicago.edu/lib/problemreport/problemreport.php)
- [x] [Circulation Can't Find it? Search Form](https://www.lib.uchicago.edu/research/help/catalog-help/full-record/cant-find-it-place-search-request/)  - (Not needed, old form)
- [x] [Need Help? Ask a Librarian](http://forms2.lib.uchicago.edu/lib/request/help.php?bib=11764576&barcode=106297575)
- [ ] [Alternative Text Request](http://forms2.lib.uchicago.edu/lib/searchform/alt-text-request.php?barcode=17773150&bib=1208480&status=AVAILABLE&cn=Bradley+Busenius&mail=bbusenius%40uchicago.edu&formats[]=Print&formats[]=Book) - (Needs implementation work but should be supportable - tracked in issue #363)

### Forms we will *not* support with this feature
The following are forms that do not need to be supported with this functionality either because they are baked into VuFind or interface with technology other than `CGIMAIL`.
- [Request via Inetlibrary Loan](http://forms2.lib.uchicago.edu/lib/searchform/requestFromILL.php?database=production&bib=9291257&barcode=108700150)
- [Scan and Deliver](https://requests.lib.uchicago.edu/illiad/illiad.dll?Action=10&Form=30&sid=ScanDelver&genre=docdel&barcode=106297575&volume=c.1+&callno=XXKJE947+.S767+2018&loc=D%27Angelo+Law%2C+Bookstacks&bib=11764576&title=Unlocking+EU+law&date=&issn=9781138572218)
- [Request from Mansueto](https://dldc1.lib.uchicago.edu/vufind/MyResearch/Storagerequest?bib=4307467&barcode=67942678&action=add)
- [Request from DLL Storage](https://dldc1.lib.uchicago.edu/vufind/Record/2678464/Hold?isDllStorage=true&barcode=088792649&item_id=4898576&holdtype=page&hashKey=7d7162eb590cc8d7b265f5b647a4d802#tabnav)
- [Place a Hold Request](https://dldc1.lib.uchicago.edu/vufind/Record/12031963/Hold?barcode=&item_id=10220454&holdtype=hold&hashKey=b97f7c556db0a60cad3601f9ef0aa29c#tabnav)

### Questions
1. What the heck is the [Tech Services Digitization Request Form for staff](https://dldc.lib.uchicago.edu/forms/digrequest.html)? Why is it on `dldc1` and not production? Do people use this?
2. Do we need/desire a form building interface that allows anyone to build a form in Wagtail or are we going to continue to be the people who generally build and maintain these things? Note, that even if we make it possible for editors to build their own forms, they will need to request a `CGIMAIL Surrogate` from web admin before it will work.

### Related issues
These issues will either be impacted, resolved or solved in part by this feature. We should try to knock these out to the extent possible with this implementation.
- #218
- #226
- #227 

## Relevant documentation
- [CGIMAIL documentation](https://www2.lib.uchicago.edu/keith/tmp/cgimail.html)
- [Forms analysis spreadsheet](https://uchicago.box.com/s/n3z4dfx5ztpfirbjjw1irwlywgqgyws1)
- [Form ADA guidelines](https://github.com/uchicago-library/uchicago-library.github.io/blob/master/docs/code-resources.md#forms)

**Comment by kzadrozny** [comment]
Tech Services Digitization Request Form for staff is something preservation maybe still uses? I was talking with Sherry to update a form for her, but I am unsure if it is this one. @c-blair might have more knowledge about this form and its use.

**Comment by bbusenius** [comment]
Reopening to ensure documentation is written

**Comment by bbusenius** [comment]
Initial documentation has been written on loop. I'll continue to augment it as I build out forms.

- [User documentation](https://loop.lib.uchicago.edu/departments/information-technology-and-digital-scholarship/digital-library-development-center/documentation/cgimail-forms-public-website/)
- [Developer documentation](https://loop.lib.uchicago.edu/departments/information-technology-and-digital-scholarship/digital-library-development-center/documentation/cgimail-forms-public-website-developer-documentation/)

**Comment by bbusenius** [comment]
I'm closing this ticket since documentation has been written and all of the tracked forms have been been built with the exception of the Alternative Text form which is being tracked in a separate issue (#363).
