### ISSUE TITLE
Changes to global nav for Borrow & Request

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#344]
Changes to global nav for Borrow & Request (Bottorff)
Recommended change from work group after user testing.

The change is as follows.

Current links under Borrow & Request:
Access & Privileges
Faculty, Students, and Staff
Alumni & Other Researchers
Privileges at Other Libraries
Proxy & Off-Campus Access
The proposed change adds direct links to the Faculty, Students, & Staff from Other Institutions page (renamed Researchers from Other Colleges & Universities) and the Members of the Public page (renamed Other Visitors) and removes the "Alumni & Other Researchers" index page, as well as the Privileges at Other Libraries page (which remains linked to under the Faculty, Students, & Staff page itself).

Proposed links:
Access & Privileges
Faculty, Students, & Staff
Alumni
Researchers from Other Colleges & Universities
Other Visitors
Proxy & Off-Campus Access

**Comment by dbietila** [comment]
My suggested steps for getting this done:

1. Change the page titles and slugs (Bottorff)
2. Draft nav changes with anticipated new URLs (Kathy)
3. Move pages into new locations (Kathy)
4. Push nav changes to production (Kathy)

**Comment by kzadrozny** [comment]
5. Make same changes to LibGuides navigation
6. Alert Emma to the change so she can mark it on GA stats.

**Comment by kzadrozny** [comment]
The new slugs are as so:

- Alumni: https://www.lib.uchicago.edu/borrow/access-privileges/alumni/
- Researchers from Other Colleges & Universities: https://www.lib.uchicago.edu/borrow/access-privileges/other-colleges-universities/
- Other Visitors: https://www.lib.uchicago.edu/borrow/access-privileges/visitors/

**Comment by kzadrozny** [comment]
All tasks have been completed.
