### ISSUE TITLE
Collections & Exhibits subject limit not updating

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#351]
On liblet, I've changed the subject snippet of "Area and Cultural Studies" to "Area Studies". This language has updated in most places, but not on the Subject limit menu on https://liblet.lib.uchicago.edu/collex/?view=subjects

**Comment by kzadrozny** [comment]
Found that this is hardcoded in `lib_collections/views.py`. We will fix the list now with plans to update this to be more dynamic in the future.
