### ISSUE TITLE
Modify Global Navigation on Nest

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#372]
1) Remove
Spaces & Services, and all child elements
Checkout UChicago from the Borrow & Request menu

2) Add
Paging & Pickup to Borrow & Request

3) Add a new top-level nav category for "Remote & Onsite Services"
Remote & Onsite Services

Remote & Onsite Services

Onsite Services
Paging and Pickup https://www.lib.uchicago.edu/borrow/requesting/paging/
Returns https://rooms.lib.uchicago.edu/calendar/returns/?cid=13002&t=d&d=0000-00-00&cal=13002&inc=0
UChicago Card services https://rooms.lib.uchicago.edu/reserve/carding
COVID policy for visitors

Remote Services
Scan & Deliver https://www.lib.uchicago.edu/borrow/requesting/scan-deliver/
Reserves for Faculty https://www.lib.uchicago.edu/research/teaching/course-reserves-setup/
Reserves for Students https://www.lib.uchicago.edu/borrow/borrowing/course-reserves/
Ask a Librarian https://www.lib.uchicago.edu/research/help/ask-librarian/
Instruction Support https://www.lib.uchicago.edu/research/teaching/research-instruction-courses/

Online Resources
Proxy & Off Campus Access https://www.lib.uchicago.edu/borrow/access-privileges/offcampus/
Suggest a Purchase https://www.lib.uchicago.edu/borrow/requesting/suggest-purchase/
Digital Collections https://www.lib.uchicago.edu/collex/?digital=on&view=collections
Web Exhibits https://www.lib.uchicago.edu/collex/?digital=on&view=exhibits

**Comment by kzadrozny** [comment]
These changes have been added to my local machine for review. They can be pushed to nest for testing. Prior to going live, they will need analytics tracking code.

**Comment by kzadrozny** [comment]
Testing has been completed and changes pushed to production under Issue #377
