### ISSUE TITLE
StaffPages can be created without "required" fields for PublicStaffPages

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#40]
StaffPages need unit, email, phone number, and faculty exchange, otherwise PublicStaffPages blow up. Either these should be required fields in the StaffPage model or we should make them optional in the PublicStaffPage.

**Comment by johnjung** [comment]
This is now in place on production- I fixed this on the PublicStaffPage side. If those fields are missing the PublicStaffPage side no longer blows up.
