### ISSUE TITLE
Different footer for Law pages

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#43]
Law pages should get a customized footer. The following links should be different.

Information for Faculty: http://guides.lib.uchicago.edu/lawfacultyservices
Information for Students: http://guides.lib.uchicago.edu/lawstudents
Information for Visitors: https://www.lib.uchicago.edu/law/about/access/
Facebook: https://www.facebook.com/dangelolawlibrary
Library News: http://news.lib.uchicago.edu/law/

**Comment by kzadrozny** [comment]
@dbietila Do you know if Law has a reason for keep Info for Faculty and Students on LibGuides rather than in Wagtail? Should this data be migrated over?

**Comment by dbietila** [comment]
I'm not aware of any reason. Please don't migrate anything without Todd Ito's approval, though.
