### ISSUE TITLE
CGIMail ID not mapped correctly

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#490]
**Problem**
- CGIMail to `id` is mapping to `name`
- Produces identical `ids` on one page when radio boxes or check boxes are used (ADA error)
- Changing link 147 to `const id = elm.id || elm.name || null;` did not resolve the issue.

**Example**
`About_this_material` in the radio boxes on this page: https://www.lib.uchicago.edu/search/forms/ask-scrc-or-request-scan/

**Comment by bbusenius** [comment]
@kzadrozny you probably had this right. You just needed to run `npm run watch` to generate the js bundle. I put you as a reviewer on the PR.

**Comment by kzadrozny** [comment]
Oh jeez, I can't believe I forgot to generate the bundle. Thanks for that reminder.
