### ISSUE TITLE
Code Checklist / Code Review

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#52]
## What do we want on our Dev Checklist?

**So far I only have (in no special order):**
- ADA Compliant
- Unit Tests written
- Migrations made
- Reviewer assigned to pull request
- UX Issues/Suggestions met

Once we get the list all fleshed-out, I was going to put them  into sub categories, as [Spatie does](https://github.com/spatie/checklist-going-live).

**Comment by dbietila** [comment]
Emma and I are doing some research on SEO this week. Assuming a public web product, it may be sensible to run it through Google's web developer tests:

PageSpeed Insights tester
https://developers.google.com/speed/pagespeed/insights/

Mobile-Friendly test
https://search.google.com/test/mobile-friendly

**Comment by kzadrozny** [comment]
We resolved this by coming up with a [dev workflow](https://github.com/uchicago-library/uchicago-library.github.io).
