### ISSUE TITLE
Public site edits for Aug 2

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#539]
## Code edits
- [x] Restore Spaces browse
### Nav
- [x] Remove "Bookstacks Access" and "Book a Seat" from Remote & On-site Services
- [x] Restore "Checkout UChicago" link under Borrow & Request
### Footer
- [x] Change Information For section to only have the `Patrons with Disabilities` link
- [x] Move the Policies section under Information For
- [x] Move `Privacy Statement` and `University Accessibility` links under Policies

## Wagtail edits
- [ ] Remove "Reserve Seats" widget from https://www.lib.uchicago.edu/ and https://www.lib.uchicago.edu/mansueto/
- [ ] Add granular hours back to Mansueto sidebar
- [ ] Update links "The Library is Ready to Help You During COVID-19" widget
   - [ ] Recent Announcements: Replace with new News story link
   - [ ] Information For: Remove "Reserving a Study Seat" and "Bookstacks Appointments"

## Guides
- [ ] remind guide authors to check COVID-related information on guides prior to Aug. 2 (@dbietila)
- [ ] Duplicate nav bar changes from public site to guide nav

**Comment by dbottorff** [comment]
There will also be some changes needed to the Hours page, but I'm not 100% certain what they will be. Once I am, I'll include them as a comment here

**Comment by dbottorff** [comment]
Also, since I've confirmed via testing that I cannot set a published page to publish a saved draft at a future time, there will be a number of Access pages that will need to have their drafts published August 2. I'm going to see if Sean Dempsey can do most of these.

**Comment by dbottorff** [comment]
Was the Spaces browse page being published and/or restored to the nav bar?

**Comment by dbottorff** [comment]
For the Hours page, the following changes can be made immediately:

- unsuppress building hours for Crerar, Mansueto, Regenstein, Social Work
- change Social Work eligible users language to read: "Eligible users: Social Work Library is open only to current Crown Family School faculty, students, and staff."
- unsuppress Eckhart address and google map link
- display link to Mansueto and Regenstein homepages again, to match other locations.

These changes can all be made immediately, as LibCal setup is already in place.

**Comment by kzadrozny** [comment]
> Also, since I've confirmed via testing that I cannot set a published page to publish a saved draft at a future time, there will be a number of Access pages that will need to have their drafts published August 2. I'm going to see if Sean Dempsey can do most of these.

**Comment by dbietila** [comment]
The following is Julie's proposal regarding Info For links:
Rebecca and I would like to move forward with unpublishing the following “Information for” pages:

Students
Faculty
Staff
Alumni
Visitors

I have summarized our reasoning below, in case there are questions. We recognize that the footer must be redesigned before the pages should be unpublished. May I loop Kathy in to move forward? Or, what should be my next steps?

Thank you,

Julie

 

Proposal to Unpublish ‘Information For’ Pages
Julie Piacentine
July 23, 2021

In consultation with Rebecca Starkey, Head of Research and Instruction Services, we propose unpublishing the ‘Information For’ library web pages for the following groups:

Students
Faculty
University Staff
Visitors
Alumni and Library Friends
 

Reasons for Unpublishing:

Use of the pages is low.
Information is redundant with that available on others, primarily the Access and Privileges pages. 
 
Next Steps:
Schedule Footer updates with DLDC staff/Kathy Zadrozny
Announce changes in WCG for dissemination to library units
Unpublish pages
