### ISSUE TITLE
Map lookups in VuFind

### ISSUE THREAD

**Issue by johnjung** [uchicago-library/library_website#56]
The map lookup script takes a long time to respond for the following item:
https://catalog.lib.uchicago.edu/vufind/Record/1216824

I traced this to OLE's SRU service. In this case the map lookup code on forms2.lib is only using the SRU to get information that is actually already available to VuFind. If we were to move the map lookup script into VuFind it would eliminate problems like this. 

Look for VuFind pull requests related to this issue and see if there is a way to share code back with the community.

**Comment by bbusenius** [comment]
This is closed since the SRU dependency has been removed and the links now load asynchronously (and fast).
