### ISSUE TITLE
EEE's Loop staff page has 500 error

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#57]
Elizabeth's Loop page pulls-up an internal error, but her public page loads without issue. I believe her Loop page cannot load due to an error with her department structure (she being the head and the only staff in her department.)

**Notes:**
- The [Loop Assessment page](https://loop.lib.uchicago.edu/units/collection-services/access-services/assessment/) loads without issue and has EEE as the head.
- While her "Position status" is incorrect, changing it doesn't remove the error. Additionally, it seems all staff are set to "clerical."

**Comment by johnjung** [comment]
Please confirm that this issue still exists, it seems to work for me: https://loop.lib.uchicago.edu/staff/elizabeth-edwards/.

**Comment by kzadrozny** [comment]
It seems that this issue has resolved itself.
