### ISSUE TITLE
Possible typo in "Staff listing" content type

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#576]
SiteImprove is complaining about an "empty container" element on https://www.lib.uchicago.edu/research/scholar/about-us/ . When I view source on this page, the table containing the "Staff listing" entries seems to be improperly closed. Instead of a </table> element, there is another <table> element at the end.

Could this be an error in the Staff Listing content type? Staff listing is a piece of templated content, rather than something I can edit directly.

**Comment by bufordrat** [comment]
This closing tag was added in #578.
