### ISSUE TITLE
Radio buttons on CGIMail forms allow more than one selection

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#611]
## Expected behavior
When a radio button is clicked, it should toggle the selection. Two radio buttons should never be selectable in the same group.

## Actual behavior
[On this form, multiple radio buttons can be selected at the same time](https://liblet.lib.uchicago.edu/search/forms/need-help-ask-librarian/?bib=12750691&barcode=117524611&subject=Ask+a+Librarian+Library+Catalog%3A+Beasts+of+ruin&referrer=https%3A%2F%2Fcatalog.lib.uchicago.edu%2Fvufind%2FRecord%2F12750691).

![image](https://user-images.githubusercontent.com/7826429/190482515-6da9538a-fcdd-43c3-ac38-4b4faa6598c7.png)

It's unclear if this is related to how the radio buttons are grouped in the JSON configuration or how it was coded (though likely the latter).

### Steps to reproduce
Go to the above form and try toggling the radio button options. They will all end up selected and cannot be unselected.

## Other information:**
https://github.com/uchicago-library/library_website/wiki/React-and-Wagtail

**Comment by bluairis** [comment]
In wagtail I made the names the same for both the yes and the no radio buttons and they now behave normally.
