### ISSUE TITLE
New Widget for "Explore Research Guides"

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#619]
We need to develop a new widget, available on Standard Pages on the Public Site, for featuring Research Guides.

The current widget used for this is a Rich Text box. This need to be retained as an option, since it is still used on the Law Library homepage and other locations. We will want to retain the look and feel of the current Research Guides presentation on https://www.lib.uchicago.edu/ when designing the new widget.

The Research Guides widget would allow queuing of content blocks with date ranges assigned, like the Featured Library Expert widget.

A global field for the widget would be:
_View All Guides URL_
This is the URL that will be linked for the "View All Guides" text on the top right of the widget.

For each content block that can be queued within the Widget, we will need the following fields.
_Section 1 Name_ text string

_Section 2 Name_ text string

Each section may have one or two guides associated with it. The guides will each be defined by two fields:
_Guide Name_ text string
_Guide URL_ URL

Finally each content block with have date values that determine when it will be active and displayed on the page:
_Start Date_ date
_End Date_ date

Overall, this should behave a lot like the Featured Library Expert widget, which should be consulted.

**Comment by bbusenius** [comment]
@dbietila, I documented the new functionality here: https://loop.lib.uchicago.edu/departments/digital-strategy-services/digital-library-development-center/documentation/link-queue-functionality-for-featured-guides-section/

We're still in the code review phase, however, I'll put it up on nest soon and set it up so you can mess with it.
