### ISSUE TITLE
Collex Browse Resets filters when limited to "web exhibits"

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#62]
After applying filters, such as subject, to the exhibit browse view, if you check "web exhibits" as a limit, it clears all filters and shows a view of ALL web exhibits.

For example: Exhibits filtered to the subject Math: https://www.lib.uchicago.edu/collex/?view=exhibits&subject=Science%2C%20Technology%2C%20and%20Math
Refreshes to all web exhibits when the limit is applied: https://www.lib.uchicago.edu/collex/?digital=on&view=exhibits&subject=Science%252C%2520Technology%252C%2520and%2520Math

The URL is passing "Math," but it doesn't seem to honor that filter.

**Comment by johnjung** [comment]
Fixed in commit 304577.
