### ISSUE TITLE
Add new Google Analytics tag to BMRC sites

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#651]
```
<!-- Google tag (gtag.js) --> 
<script async src="https://www.googletagmanager.com/gtag/js?id=G-K06JQM9CM5 "></script> <script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-K06JQM9CM5 ');
</script>
```
Please add this code to the <head> element of pages in the BMRC wagtail instance.

**Comment by dbietila** [comment]
I think that is the old tag. The “UA” prefix indicates that it is a Universal Analytics, which is the old version. I think we need to swap in the identifier in the ticket: G-K06JQM9CM5 , which is a GA4 account.

We should also check and see whether this change applies to the BMRC portal, or if we need to do that separately.

**Comment by dbietila** [comment]
I've added John to the ticket, in case there's anything he needs to look at.

**Comment by bbusenius** [comment]
This is done on the BMRC website. I'm not sure about the portal.

**Comment by dbietila** [comment]
I'm still seeing the old tag (UA-157097671-1) in the source. Do we need to clear cache or anything for the new one (G-K06JQM9CM5) to show up?

**Comment by bbusenius** [comment]
Looks like I forgot to run the `collectstatic` command and restart the server. It's there now.

**Comment by dbietila** [comment]
Yes, looks good now. I don't think the portal needs any extra attention.

**Comment by bbusenius** [comment]
Good to know. Closing this.
