### ISSUE TITLE
Nav edits for Access and Preservation

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#683]
Please see https://docs.google.com/spreadsheets/d/1O-1GSLPwdpq5iBjckQZduVPmvqjSJ-IQ4hcb2y4AdZ0/edit?usp=sharing for a summary of changes to the global nav. Please apply these changes to Wagtail, LibGuides, and any other platforms requiring the global nav.

**Comment by bbusenius** [comment]
I updated the nav on the Library website, Libguides and LibCal.l
