### ISSUE TITLE
Upgrade Django and Wagtail

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#778]
## Issue
We're currently running `Django 4.1.13` and `Wagtail 4.1.9`. We should upgrade to `Django 5.0.7` and `Wagtail 6.1.3`.

### Python Release Notes
https://docs.python.org/3/whatsnew/3.10.html
https://docs.python.org/3/whatsnew/3.11.html

### Django Release Notes
https://docs.djangoproject.com/en/5.0/releases/4.2/
https://docs.djangoproject.com/en/5.0/releases/5.0/

### Wagtail Release Notes
https://docs.wagtail.org/en/stable/releases/4.2.html
https://docs.wagtail.org/en/stable/releases/5.0.html
https://docs.wagtail.org/en/stable/releases/5.1.html
https://docs.wagtail.org/en/stable/releases/5.2.html
https://docs.wagtail.org/en/stable/releases/6.0.html
https://docs.wagtail.org/en/stable/releases/6.1.html

**Comment by vitorgomateus** [comment]
New in Wagtail 6.1
[Universal listings continued](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/#universal-listings-continued)
[Information-dense admin interface](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/#information-dense-admin-interface)
[Keyboard shortcuts overview](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/#keyboard-shortcuts-overview)
[Better guidance for password-protected content](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/#better-guidance-for-password-protected-content)
[Other user interface refinements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/#other-user-interface-refinements)
New in Wagtail 6.0
[Universal listings](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-0/#universal-listings)
[Right-to-left language support](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-0/#right-to-left-language-support)
[Accessibility checker in page editor](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-0/#accessibility-checker-in-page-editor)
[Polished dark mode](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-0/#polished-dark-mode)
[Page types usage report](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-0/#page-types-usage-report)
[Accessibility improvements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-0/#accessibility-improvements)
New in Wagtail 5.2
[Redesigned page listing view](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-2/#redesigned-page-listing-view)
[User interface refinements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-2/#user-interface-refinements)
[External links in promoted search results](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-2/#external-links-in-promoted-search-results)
[Subject and body for email links](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-2/#subject-and-body-for-email-links)
[Site-specific improvements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-2/#site-specific-improvements)
[Wagtail user interface extensions with Stimulus](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-2/#wagtail-user-interface-extensions-with-stimulus)
[Content management features beyond pages](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-2/#content-management-features-beyond-pages)
New in Wagtail 5.1
[Read-only panels](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-1/#read-only-panels)
[AVIF image support](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-1/#avif-image-support)
[Accessibility improvements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-1/#accessibility-improvements)
[Dark mode improvements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-1/#dark-mode-improvements)
[General UI improvements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-1/#general-ui-improvements)
New in Wagtail 5.0
[Object usage information on deleting objects](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-0/#object-usage-information-on-deleting-objects)
[SVG image support](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-0/#svg-image-support)
[Accessibility checker improvements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-0/#accessibility-checker-improvements)
[Always-on minimap](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-0/#always-on-minimap)
[Dark mode](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-5-0/#dark-mode)
New in Wagtail 4.2
[Supercharged snippets](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-4-2/#supercharged-snippets)
[Multiple chooser panel](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-4-2/#multiple-chooser-panel)
[Resizable side panels](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-4-2/#resizable-side-panels)
[Built-in accessibility checker](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-4-2/#built-in-accessibility-checker)
[Rich text improvements](https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-4-2/#rich-text-improvements)
