### ISSUE TITLE
link to Crerar staff is not filtering correctly

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#82]
The link to "Departments and Staff" on the left sidebar of Crerar pages ( https://www.lib.uchicago.edu/crerar/ ) is supposed to link to a view of the staff directory filtered to Science Libraries staff only. Instead, it currently links to all staff even though the URL has science library filter parameters: https://www.lib.uchicago.edu/about/directory/?department=Science+Libraries&view=staff

**Comment by johnjung** [comment]
I updated the link in the redirect page to https://www.lib.uchicago.edu/about/directory/?view=staff&department=Research%20%26%20Learning%20-%20Science%20Libraries. 

(You need to specify the full form of a department name in the URL parameter.)
