### ISSUE TITLE
Staff Profile Page: Location link is empty

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#85]
## Expected behavior
Location link in sidebar should go to the location in the Directory.
Example: [Law Staff](https://www.lib.uchicago.edu/about/directory/staff/todd-ito/) page, link should go to [Law staff listing](https://www.lib.uchicago.edu/about/directory/?view=staff&library=The%20D%27Angelo%20Law%20Library) in the Directory.

## Actual behavior
The link is empty, producing a `#`

### Steps to reproduce
Example [staff page](https://www.lib.uchicago.edu/about/directory/staff/todd-ito/)

**Comment by johnjung** [comment]
This will be relatively complicated to fix. For some reason, the department shows up on Todd's page as "D'Angelo Law Library". However, the staff directory browse requires the string "The D'Angelo Law Library". I'm curious if it's possible for us to avoid the problem by converting the link to plain text in this case. If the user navigated to this page via the staff directory, and they decide that this specific staff person isn't the right one to contact, they can return to the staff directory and browse staff in lots of different ways. 

Alternatively, I can look into why the two different forms of library names exist in the system and I can standardize them. In that case, links like this will work correctly.

**Comment by johnjung** [comment]
Standardized different forms of library names- this is now fixed.
