### ISSUE TITLE
Need a nested view of Subject snippets

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#87]
Subjects in Wagtail can have multiple parents. The Guides subgroup would like an alternative to the view on https://www.lib.uchicago.edu/collex/?view=subjects that organizes the Subject list according to these parent/child relationships. This may be of interest to site users, so developing as a page for public display would probably have some value.

**Comment by johnjung** [comment]
@dbietila, I have a few questions about this one. Where should this page live? Will it replace that subject view, or will it have a different URL? We can code this up to use nested lists to show parent-child relationships, and child nodes will repeat in cases where a node has more than one parent. Should there be any other information on this page, to describe each subject? Should each subject link to its entry on the collex link above?

**Comment by dbietila** [comment]
It should be a new page. I think something like https://www.lib.uchicago.edu/collex/?view=subjecttree would be fine. 

Compared to https://www.lib.uchicago.edu/collex/?view=subjects , you can eliminate the right column. Retaining the middle column information would be good, if possible. If that makes things a pain, you could just link back to the entry on https://www.lib.uchicago.edu/collex/?view=subjects.

**Comment by johnjung** [comment]
This should be finished. Here is the view:
https://www.lib.uchicago.edu/collex/?view=subjecttree

I'll close this issue out, but please reopen it if necessary.
