### ISSUE TITLE
Unpublished & Inactive Staff show up in Directory views

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#91]
## Expected behavior

When a Wagtail user is marked as inactive and their staff pages are unpublished, we expect that the staff will not show up in department or subject browse results.

## Actual behavior

Using Paul as an example, he shows up in both the [Department browse](https://www.lib.uchicago.edu/about/directory/?view=staff&library=Social%20Service%20Administration%20Library&subject=Social%20Sciences) results and in [Subject browse](https://www.lib.uchicago.edu/about/directory/?view=staff&department=Research%20%26%20Learning%20-%20Research%20and%20Teaching%20Support%20-%20Social%20Sciences%20-%20Social%20Service%20Administration%20Library%20%28SSA%29) results

**Comment by johnjung** [comment]
I fixed this in units/views.py- there were two cases, one for departmental browsing and one for subject browsing, where we weren't restricting staff pages to pages that were published only. I updated those and looked through the rest of the directory code for good measure- everything else looks like it's restricted to live pages only. 

Closing this bug out, please feel free to reopen if we find more cases like this.
